AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Amplify deployment for Next.js real estate application

Parameters:
  Stage:
    Type: String
    Description: Deployment stage (e.g., dev, prod)
    Default: dev
  ProjectName:
    Type: String
    Description: Name of the projects
    Default: slt-web
  GitHubRepository:
    Type: String
    Description: GitHub repository URL

  GitHubBranch:
    Type: String
    Description: GitHub branch to deploy
    Default: main

  GitHubToken:
    Type: String
    Description: GitHub personal access token
    NoEcho: true

  NextAuthUrl:
    Type: String
    Description: NextAuth URL for authentication

  NextPublicApiUrl:
    Type: String
    Description: Supabase project URL

  NextPublicApiKey:
    Type: String
    Description: Supabase public API key

  AuthSecret:
    Type: String
    Description: Auth secret for JWT signing
    NoEcho: true

  NextImagesUrl:
    Type: String
    Description: URL for Next.js images

  GoogleClientId:
    Type: String
    Description: Google OAuth Client ID
    Default: ''

  GoogleClientSecret:
    Type: String
    Description: Google OAuth Client Secret
    NoEcho: true
    Default: ''

Resources:
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: !Sub '${ProjectName}-${Stage}-app'
      Description: !Sub 'Amplify App for ${ProjectName} in ${Stage} stage'
      Repository: !Ref GitHubRepository
      AccessToken: !Ref GitHubToken
      BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - npm ci --cache .npm --prefer-offline
            build:
              commands:
                - env | grep -e NEXTAUTH_URL >> .env.production
                - env | grep -e AUTH_SECRET >> .env.production
                - env | grep -e NEXT_PUBLIC_API_URL >> .env.production
                - env | grep -e NEXT_PUBLIC_API_KEY >> .env.production
                - env | grep -e NEXT_IMAGES_URL >> .env.production
                - env | grep -e STAGE >> .env.production
                - env | grep -e PROJECT_NAME >> .env.production
                - env | grep -e GOOGLE_CLIENT_ID >> .env.production
                - env | grep -e GOOGLE_CLIENT_SECRET >> .env.production
                - npm run build
          artifacts:
            baseDirectory: .next
            files:
              - '**/*'
          cache:
            paths:
              - 'node_modules/**/*'
              - '.next/cache/**/*'
              - '.npm/**/*'
      EnvironmentVariables:
        - Name: NEXTAUTH_URL
          Value: !Ref NextAuthUrl
        - Name: AUTH_SECRET
          Value: !Ref AuthSecret
        - Name: NEXT_PUBLIC_API_URL
          Value: !Ref NextPublicApiUrl
        - Name: NEXT_PUBLIC_API_KEY
          Value: !Ref NextPublicApiKey
        - Name: NEXT_IMAGES_URL
          Value: !Ref NextImagesUrl
        - Name: STAGE
          Value: !Ref Stage
        - Name: PROJECT_NAME
          Value: !Ref ProjectName
        - Name: GOOGLE_CLIENT_ID
          Value: !Ref GoogleClientId
        - Name: GOOGLE_CLIENT_SECRET
          Value: !Ref GoogleClientSecret
        - Name: _LIVE_UPDATES
          Value: '[{"name":"Next.js version","pkg":"next","type":"npm","version":"latest"}]'
      IAMServiceRole: !GetAtt AmplifyRole.Arn
      Platform: WEB_COMPUTE
      CustomRules:
        - Source: /<*>
          Target: /index.html
          Status: 404-200
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Stage
          Value: !Ref Stage

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: !Ref GitHubBranch
      EnableAutoBuild: true
      EnablePullRequestPreview: false
      Framework: Next.js - SSR
      Stage: PRODUCTION

  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess-Amplify
      Policies:
        - PolicyName: AmplifyDeploymentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
  ##A subdomain cannot point to a non-existent branch (Service: Amplify, Status Code: 400
  AmplifyDomain:
    Type: AWS::Amplify::Domain
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      DomainName: !Sub ${AmplifyApp.AppId}.amplifyapp.com
      EnableAutoSubDomain: true
      SubDomainSettings:
        - Prefix: !Ref GitHubBranch
          BranchName: !Ref GitHubBranch

Outputs:
  AppId:
    Description: Amplify App ID
    Value: !GetAtt AmplifyApp.AppId
    Export:
      Name: !Sub ${AWS::StackName}-AppId

  AppUrl:
    Description: Amplify App URL
    Value: !Sub https://${GitHubBranch}.${AmplifyApp.DefaultDomain}
    Export:
      Name: !Sub ${AWS::StackName}-AppUrl

  BranchName:
    Description: Amplify Branch Name
    Value: !Ref GitHubBranch
    Export:
      Name: !Sub ${AWS::StackName}-BranchName
